[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn run:app --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
PYTHON_VERSION = "3.9.18"
