"""add audit log table

Revision ID: 00834c26db71
Revises: 5212cb9e78dc
Create Date: 2025-07-12 02:54:24.795241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00834c26db71'
down_revision = '5212cb9e78dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporte_id'], ['credit_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('fecha_accion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='audit_logs_company_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.drop_table('audit_log')
    # ### end Alembic commands ###
