"""add nacionalidad to user

Revision ID: 2b0cddc9a52e
Revises: 88b64e428b0f
Create Date: 2025-05-06 05:37:24.180855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0cddc9a52e'
down_revision = '88b64e428b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=5), nullable=False, server_default='V'))
        batch_op.create_index(batch_op.f('ix_user_cedula'), ['cedula'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nacionalidad'), ['nacionalidad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nacionalidad'))
        batch_op.drop_index(batch_op.f('ix_user_cedula'))
        batch_op.drop_column('nacionalidad')

    # ### end Alembic commands ###
