"""Add ultima_consulta column to users table

Revision ID: 5212cb9e78dc
Revises: 
Create Date: 2025-07-11 17:15:45.165792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5212cb9e78dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_resolucion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario_admin', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prioridad', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        # Convertir consultas_realizadas_mes de VARCHAR a INTEGER usando USING
        op.execute("ALTER TABLE company ALTER COLUMN consultas_realizadas_mes TYPE INTEGER USING consultas_realizadas_mes::INTEGER")
        # Convertir ultima_consulta de VARCHAR a TIMESTAMP usando USING
        op.execute("ALTER TABLE company ALTER COLUMN ultima_consulta TYPE TIMESTAMP USING ultima_consulta::TIMESTAMP")
        batch_op.drop_column('sector_economico')
        batch_op.drop_column('certificacion_digital')
        batch_op.drop_column('telefono_empresa')
        batch_op.drop_column('direccion_fiscal')
        batch_op.drop_column('tipo_empresa')
        batch_op.drop_column('fecha_constitucion')
        batch_op.drop_column('capital_social')
        batch_op.drop_column('categoria_empresa')
        batch_op.drop_column('representante_legal')
        batch_op.drop_column('cedula_representante')
        batch_op.drop_column('empleados_count')
        batch_op.drop_column('limite_consultas_mes')

    with op.batch_alter_table('consulta_credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_consulta', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resultado_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))

    with op.batch_alter_table('credit_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('institucion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('plazo_meses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tasa_interes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cuota_mensual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dias_mora', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_ultimo_pago', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('saldo_actual', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_consulta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_user_cedula')
        batch_op.drop_index('ix_user_nacionalidad')
        batch_op.create_index(batch_op.f('ix_users_cedula'), ['cedula'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nacionalidad'), ['nacionalidad'], unique=False)
        batch_op.drop_column('telefono_trabajo')
        batch_op.drop_column('direccion_trabajo')
        batch_op.drop_column('tiempo_empleo_meses')
        batch_op.drop_column('empresa_trabajo')
        batch_op.drop_column('probabilidad_default')
        batch_op.drop_column('score_historial')
        batch_op.drop_column('bloqueado_hasta')
        batch_op.drop_column('factores_riesgo')
        batch_op.drop_column('intentos_login')
        batch_op.drop_column('ultimo_login')
        batch_op.drop_column('telefono_verificado')
        batch_op.drop_column('categoria_riesgo')
        batch_op.drop_column('email_verificado')
        batch_op.drop_column('documento_verificado')
        batch_op.drop_column('dependientes')
        batch_op.drop_column('fecha_verificacion')
        batch_op.drop_column('nivel_educativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_educativo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_verificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dependientes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('documento_verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categoria_riesgo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono_verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ultimo_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intentos_login', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('factores_riesgo', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bloqueado_hasta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score_historial', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('probabilidad_default', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('empresa_trabajo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tiempo_empleo_meses', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion_trabajo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono_trabajo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_nacionalidad'))
        batch_op.drop_index(batch_op.f('ix_users_cedula'))
        batch_op.create_index('ix_user_nacionalidad', ['nacionalidad'], unique=False)
        batch_op.create_index('ix_user_cedula', ['cedula'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('ultima_consulta')

    with op.batch_alter_table('credit_history', schema=None) as batch_op:
        batch_op.drop_column('saldo_actual')
        batch_op.drop_column('fecha_ultimo_pago')
        batch_op.drop_column('dias_mora')
        batch_op.drop_column('cuota_mensual')
        batch_op.drop_column('tasa_interes')
        batch_op.drop_column('plazo_meses')
        batch_op.drop_column('institucion')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('consulta_credito', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('resultado_score')
        batch_op.drop_column('tipo_consulta')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_consultas_mes', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('empleados_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cedula_representante', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('representante_legal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categoria_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capital_social', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_constitucion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion_fiscal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certificacion_digital', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sector_economico', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('ultima_consulta',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('consultas_realizadas_mes',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('sector')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prioridad')
        batch_op.drop_column('comentario_admin')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('fecha_resolucion')

    # ### end Alembic commands ###
