"""add cedula y nacionalidad a Appeal

Revision ID: 88b64e428b0f
Revises: 7ea61891805f
Create Date: 2025-05-06 04:55:23.179182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b64e428b0f'
down_revision = '7ea61891805f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=5), nullable=True))
        batch_op.create_index(batch_op.f('ix_appeal_cedula'), ['cedula'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeal_nacionalidad'), ['nacionalidad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeal_nacionalidad'))
        batch_op.drop_index(batch_op.f('ix_appeal_cedula'))
        batch_op.drop_column('nacionalidad')
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
