"""add PagoPlan model for portal de pagos

Revision ID: b923b4960b71
Revises: 00834c26db71
Create Date: 2025-07-12 04:34:49.104464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b923b4960b71'
down_revision = '00834c26db71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('tipo_pago', sa.String(length=50), nullable=False),
    sa.Column('moneda', sa.String(length=20), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('titular', sa.String(length=120), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=False),
    sa.Column('fecha_transferencia', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_suscripcion', sa.DateTime(), nullable=True),
    sa.Column('fecha_suspension', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('comentario_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_plan')
    # ### end Alembic commands ###
